### ISSUE TITLE
Fix Navbar 

### ISSUE THREAD

**Issue by rolikaagarwal** [AbhiPatel10/AISKCON-CONSTRUCTION#352] opened 2023-06-10 18:36 UTC
![image](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/81984963/f350a56b-6b68-4afa-a1cd-0e6d1e6773ec)

Fix this issue in the navbar. When we scroll down the navbar is showing unexpected behaviour.

**Comment by Neha5679** [comment] 2023-06-11 01:42
As a part of GSSOC'23,
I would like to work on it. So, can you provide me.

**Comment by Diya28-mehra** [comment] 2023-06-11 11:58
I want to work on this issue. Please assign me this

**Comment by kartikayasija** [comment] 2023-06-11 17:32
Go ahead @Neha5679 , Try to complete it asap.

**Comment by Neha5679** [comment] 2023-06-16 04:38
I tried but the issue is not resolved yet. Their is no issue during scroll
up. But issue comes during scroll down. Already use sticky and top 0 but
their is margin on top during scroll down.

**Comment by ritik48** [comment] 2023-06-16 05:47
@Neha5679 actually it's happening due to position: sticky on navBar1. I searched about it and found out sticky has buggy jump behavious. So I changed position: sticky to fixed and then it got resolved.

**Comment by Neha5679** [comment] 2023-06-16 06:16
Yes, it's working but then more issues comes after that so need to resolve
navbar width and h1 in hero section. I done it, can you go through once
maybe it resolved now

**Comment by ritik48** [comment] 2023-06-16 07:50
@Neha5679 Actually I have already created a pr for this issue. Let's see if it gets merged.
You can see the required code changes I made in this pr #373

**Comment by kartikayasija** [comment] 2023-06-16 16:36
@Neha5679 @ritik48 This bug is being caused by background attachment properties of Why choose Us Section.
Try to fix that, the sticky position of navbar is totally find.

**Comment by ritik48** [comment] 2023-06-16 16:55
@kartikayasija thanks for the help. I have updated my pr, please review it.

**Closed** 2023-06-17 06:59 UTC
Labels: gssoc23, level2
