### ISSUE TITLE
Add transition to button [GSSoc'23]

### ISSUE THREAD

**Issue by ChinatuL** [AbhiPatel10/AISKCON-CONSTRUCTION#108] opened 2023-05-20 06:13 UTC
The Book Us button in the hero section has no transition on hover like the other buttons. 

![Screenshot (128)](https://github.com/AbhiPatel10/AISKCON-CONSTRUCTION/assets/97689140/a36ad8f4-b237-454a-be0c-c6179e94670f)

I would love to fix this as a Gssoc23 contributor.

**Comment by VanshKing30** [comment] 2023-05-20 06:35
I would Love To fix this issue , this seems pretty interesting the simple button's look very simple 
I will add an amazing animation after hover on button 
Please assign this to me

**Comment by ChinatuL** [comment] 2023-05-20 06:37
> I would Love To fix this issue , this seems pretty interesting the simple button's look very simple I will add an amazing animation after hover on button Please assign this to me

I am also a contributor and to fix an issue you have to open one. I will be fixing this one since I opened it. You can check the site for other bugs or enhancements. Thank you

**Comment by VanshKing30** [comment] 2023-05-20 06:39
> > I would Love To fix this issue , this seems pretty interesting the simple button's look very simple I will add an amazing animation after hover on button Please assign this to me
> 
> I am also a contributor and to fix an issue you have to open one. I will be fixing this one since I opened it. You can check the site for other bugs or enhancements. Thank you

It is not necessary that the person who opens up the issue is the only one who will be the solving the issue

**Comment by ChinatuL** [comment] 2023-05-20 06:41
> > > I would Love To fix this issue , this seems pretty interesting the simple button's look very simple I will add an amazing animation after hover on button Please assign this to me
> > 
> > 
> > I am also a contributor and to fix an issue you have to open one. I will be fixing this one since I opened it. You can check the site for other bugs or enhancements. Thank you
> 
> It is not necessary that the person who opens up the issue is the only one who will be the solving the issue

Alright then. Let's wait for the maintainer to assign.

**Comment by imrish4** [comment] 2023-05-20 08:42
Please assign me this issue under GSSOC 23

**Comment by Apreksha** [comment] 2023-05-20 13:33
Hello @AbhiPatel10. I'm a GSSoC'23 contributor. I can add hover effects to the Book us button. Could you please assign me this task.

**Comment by Shenon10** [comment] 2023-05-20 19:08
Hello @AbhiPatel10 sir, I am a GSSOC contributor. Please assign me this task.

**Comment by kartikayasija** [comment] 2023-05-23 19:51
Go ahead @ChinatuL ! Try to add a good hover effect on this button

**Comment by ChinatuL** [comment] 2023-05-23 21:52
Thank you @kartikayasija . Kindly add the Gssoc'23 label as I am one of the contributors.

**Closed** 2023-05-24 08:59 UTC

**Comment by ChinatuL** [comment] 2023-05-24 09:06
Thank you. Kindly add the Gssoc'23 badge so my contribution will count.

**Comment by ChinatuL** [comment] 2023-05-24 09:06
Also, I would like to add the same transition effect to all the other buttons. Can I open an issue for that?

**Comment by kartikayasija** [comment] 2023-05-24 09:12
@ChinatuL I think someone is working on the same, if by some reason he could not raise the PR, then you can work on this issue.

**Comment by ChinatuL** [comment] 2023-05-24 09:17
Alright then. I have seen the raised issue. I will wait to see if any PR is raised.
